<a href="https://colab.research.google.com/github/SuryARavichan/NUMPY-FULL-BASICS/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('surya')

surya


In [2]:
4

4

In [3]:
7

7

In [4]:
a = 4
b = 18989


In [5]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)

18993
-18985
75956
0.0002106482700510822
0


In [6]:
for x in range(5):
  print(' oh my god! ')

 oh my god! 
 oh my god! 
 oh my god! 
 oh my god! 
 oh my god! 


In [8]:
i = 50
while i > 100:
  print('greater number!')
else:
  print('number is smaller!')

number is smaller!


In [19]:
num = int(input('enter the number ?'))
if num > 10:
  print('positive number')
elif num < -1:
  print('not upto the limit')
else:
  print('negative number')


enter the number ?-4
not upto the limit


In [20]:
import numpy as np

In [21]:
a = [12,45,78,90]


In [22]:
np.array(a)

array([12, 45, 78, 90])

In [23]:
np.amax(a)

90

In [24]:
np.amin(a)

12

In [25]:
np.argmax(a)

3

In [26]:
np.argmin(a)

0

In [27]:
np.mean(a)

56.25

In [28]:
np.std(a)

30.400452299266863

In [30]:
np.var(a)

924.1875

In [31]:
np.max(a)


90

In [32]:
np.min(a)

12

In [33]:
np.amin(a)

12

In [34]:
np.absolute(a)

array([12, 45, 78, 90])

In [35]:
np.angle(a)

array([0., 0., 0., 0.])

In [38]:
np.angle(a)

array([0., 0., 0., 0.])

In [40]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
np.arccosh(a)

array([3.17631318, 4.49968619, 5.04981491, 5.19292599])

In [43]:
np.arcsin(a)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arcsin
  """Entry point for launching an IPython kernel.


array([nan, nan, nan, nan])

In [44]:
np.average(a)

56.25

In [45]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [46]:
np.tan(a) 

array([-0.63585993,  1.61977519, -0.59918   , -1.99520041])

In [47]:
np.conj(a)

array([12, 45, 78, 90])

In [49]:
np.ceil(a)

array([12., 45., 78., 90.])

In [50]:
np.cumsum(a)

array([ 12,  57, 135, 225])

In [51]:
np.cumproduct(a)

array([     12,     540,   42120, 3790800])

In [53]:
np.median(a)

61.5

In [54]:
np.product(a)

3790800